import type { ConfigFile } from '../types/config.js'

export const DEFAULT_IGNORE_PATTERNS = [
  'node_modules',
  '**/node_modules',
  '.git',
  '**/.git',
  'dist',
  '**/dist',
  'build',
  '**/build',
  'coverage',
  '**/coverage',
  '.next',
  '**/.next',
  '.nuxt',
  '**/.nuxt',
  '.svelte-kit',
  '**/.svelte-kit',
  '.astro',
  '**/.astro',
  '*.log',
  '**/*.log',
  'package-lock.json',
  '**/package-lock.json',
  'yarn.lock',
  '**/yarn.lock',
  'pnpm-lock.yaml',
  '**/pnpm-lock.yaml',
  '.env',
  '**/.env',
  '.env.*',
  '**/.env.*',
  '.DS_Store',
  '**/.DS_Store',
  'Thumbs.db',
  '**/Thumbs.db',
  '.vscode',
  '**/.vscode',
  '.idea',
  '**/.idea',
  'codemerge.json',
  '**/codemerge.json',
  'codemerge.config.json',
  '**/codemerge.config.json'
]

export const DEFAULT_INCLUDE_PATTERNS = [
  'Dockerfile',
  'docker-compose*.yml',
  'Makefile',
  'LICENSE',
  '**/*.ts',
  '**/*.tsx',
  '**/*.js',
  '**/*.jsx',
  '**/*.vue',
  '**/*.svelte',
  '**/*.astro',
  '**/*.html',
  '**/*.css',
  '**/*.scss',
  '**/*.py',
  '**/*.go',
  '**/*.rs',
  '**/*.java',
  '**/*.cpp',
  '**/*.c',
  '**/*.cs',
  '**/*.php',
  '**/*.rb',
  '**/*.swift',
  '**/*.kt',
  '**/*.dart',
  '**/*.sql',
  '**/*.sh',
  '**/*.md',
  '**/*.mdx',
  '**/*.json',
  '**/*.yaml',
  '**/*.yml',
  '**/*.toml'
]

export const DEFAULT_CONFIG: Omit<ConfigFile, 'projectName' | 'outputPath'> = {
  port: 9876,
  useGitignore: true,
  onStartCommand: '',
  onStartCommandLogs: false,
  onUpsertCommand: '',
  ignorePatterns: DEFAULT_IGNORE_PATTERNS,
  includePatterns: DEFAULT_INCLUDE_PATTERNS
}